### PR TITLE
sorted_set optimization

### PR DESCRIPTION
**Pull request by weixsong**
performance test: http://jsperf.com/sorted-set-test

Actually, the performance is not promoted too much, and even in some case no promotion.
But the code is much more clean and easy to understand and maintain.

### CODE REVIEW

**Comment by weixsong** [comment]
Sorry for the inconvenience, I have tried to open another branch to commit the second patch, but I found that even in branch, github will put the commit together.

**Comment by weixsong** [comment]
change tf to logarithmically scaled tf, it's a little weird to use tf directly but use logarithmically scaled idf. 
reference: http://en.wikipedia.org/wiki/Tf%E2%80%93idf
So, I changed tf to logarithmically scaled tf

**Comment by weixsong** [comment]
ps: tf is weird because idf is in log scaled pattern, and, idf is totally in wrong computation.

idf shoud be inversed document frequency,  \mathrm{idf}(t, D) =  \log \frac{N}{|\{d \in D: t \in d\}|},
N: total number of documents in the corpus
but in the original code, it using this.tokenStore.length as N, which does not make any sense.

**Comment by weixsong** [comment]
in search function, tf of each token is computed
only by 1/tokens, if query contains duplicated tokens,
this doesn't make sense.

**Comment by weixsong** [comment]
trimmer optimization, see performance test:
http://jsperf.com/trimmer-improvement2

**Comment by olivernn** [comment]
Below is the method that currently calculates the IDF value:

```javascript
lunr.Index.prototype.idf = function (term) {
  var cacheKey = "@" + term
  if (Object.prototype.hasOwnProperty.call(this._idfCache, cacheKey)) return this._idfCache[cacheKey]

  var documentFrequency = this.tokenStore.count(term),
      idf = 1

  if (documentFrequency > 0) {
    idf = 1 + Math.log(this.tokenStore.length / documentFrequency)
  }

  return this._idfCache[cacheKey] = idf
}
```

It makes use of a couple of methods on `tokenStore`

```javascript
lunr.TokenStore.prototype.get = function (token, root) {
  return this.getNode(token, root).docs || {}
}

lunr.TokenStore.prototype.count = function (token, root) {
  return Object.keys(this.get(token, root)).length
}
```

I think I used the definition from [wikipedia](http://en.wikipedia.org/wiki/Tf%E2%80%93idf#Inverse_document_frequency_2) for IDF.

Looking back I think getting the document frequency is correct, since [`tokenStore.count(term)`](https://github.com/olivernn/lunr.js/blob/master/lib/token_store.js#L128-L131) gets the count of documents that contain that term. This is _not_ a very good name for this method, and also it is undocumented in the source :scream_cat:

However I think there is a bug in that it is using the [total number of tokens instead of total number of documents](https://github.com/olivernn/lunr.js/blob/master/lib/index.js#L255), e.g. `this.tokenStore.length` should really be `this.documentStore.length`.

As for the [calculation of the term frequency](https://github.com/olivernn/lunr.js/blob/master/lib/index.js#L159-L167) it is not logarithmic and I *think* for the moment this should be fine. The term frequency is calculated relative to the total length of a document to prevent longer documents out scoring shorter documents. I'm open to looking at other ways of scoring the similarity of documents and queries but I'm happy at the moment with the TF calculation, i.e. it does not contain a clear bug as in the case of the IDF calculation.

**Comment by weixsong** [comment]
@olivernn , regarding the term frequency calculation, yes, you're right, it's good and working perfect.

Regarding the idf issue, the bug about "using the total number of tokens instead of total number of documents," is sure. I will commit a new patch.

But, I have one question, currently idf is computed by: 
idf = 1 + Math.log(this.tokenStore.length / documentFrequency)

By referencing the wikipeida http://en.wikipedia.org/wiki/Tf%E2%80%93idf#Inverse_document_frequency_2, I don't know where the number 1 come from from in the calculation.
Could you give me some hint? :)

**Pull request closed without merging**
