### PR TITLE
Convert stop words filter from SortedSet/Array to Object

### PR DESCRIPTION
**Pull request by bvaughn**
The stop words filter is currently implemented using a `SortedSet` and `indexOf` method. A faster method would be to use an `Object` and its keys directly.

Here is a JS perf demonstrating the performance gains:
http://jsperf.com/lunr-stop-words-object

Existing stop words tests pass after this change.

### CODE REVIEW

**Comment by olivernn** [comment]
This looks like a good start, though there are a couple of things that need to be handled with care. JavaScript objects are not _great_ at being hashes. In this case anything on `Object.prototype` would be considered a stop word.

The best way to fix this is by creating the `stopWords` object with `Object.create(null)`, however, as far as I'm aware this is not possible to shim.

The second way, and this is the way the [`idfCache`](https://github.com/olivernn/lunr.js/blob/master/lib/index.js#L247-L260) is implemented, is to prefix all keys with some character to avoid any clashes with builtins. I've updated the [benchmarks](http://jsperf.com/lunr-stop-words-object/2) with a change like this. Might be worth running them a few times as Chrome seems to be slower now?

I think it might also be worth having this available as a function that creates stopWordFilters, just to make it simple for end users to provide their own stop word lists easily, something like:

```javascript
lunr.stopWordFilter = lunr.stopWordFilterBuilder(["long", "list", "of", "stop", "words"])
```

What do you think?

**Comment by bvaughn** [comment]
Ah, that's a fair point.

I wonder if the reason for the slow-down in the updated example is the string concatenation?

I've added a newer version of the benchmark that removes the string concatenation while (I think) also addressing your `Object.prototype` concerns. Chrome performance is back to being in the green.

**Comment by bvaughn** [comment]
PS. If you are satisfied with the updated approach (demonstrated in the JS Perf test) I'll make the corresponding changes to my PR. :)

**Comment by bvaughn** [comment]
By the way, I've updated my pull request and added an additional test to cover the `Object.prototype` concerns you mentioned.

**Comment by olivernn** [comment]
Your changes are in the [latest release](https://github.com/olivernn/lunr.js/releases/tag/v0.5.12) of lunr. I added a small change to quote all the keys of the object. Thanks again for your work on this one!

**Pull request closed without merging**
